/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AiRouteImport } from './routes/ai'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as PlacementRouteImport } from './routes/placement'
import { Route as PracticeRouteImport } from './routes/practice'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as TestRouteImport } from './routes/test'
import { Route as LessonLessonIdRouteImport } from './routes/lesson.$lessonId'
import { Route as PracticeIndexRouteImport } from './routes/practice.index'
import { Route as PracticeAccuracyRouteImport } from './routes/practice.accuracy'
import { Route as PracticeFreeRouteImport } from './routes/practice.free'
import { Route as PracticeSpeedRouteImport } from './routes/practice.speed'
import { Route as PracticeWeaknessRouteImport } from './routes/practice.weakness'
import { Route as TestIndexRouteImport } from './routes/test.index'
import { Route as TestDurationRouteImport } from './routes/test.$duration'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRoute = AiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementRoute = PlacementRouteImport.update({
  id: '/placement',
  path: '/placement',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeRoute = PracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const TestRoute = TestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonLessonIdRoute = LessonLessonIdRouteImport.update({
  id: '/lesson/$lessonId',
  path: '/lesson/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const PracticeIndexRoute = PracticeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeAccuracyRoute = PracticeAccuracyRouteImport.update({
  id: '/accuracy',
  path: '/accuracy',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeFreeRoute = PracticeFreeRouteImport.update({
  id: '/free',
  path: '/free',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeSpeedRoute = PracticeSpeedRouteImport.update({
  id: '/speed',
  path: '/speed',
  getParentRoute: () => PracticeRoute,
} as any)
const PracticeWeaknessRoute = PracticeWeaknessRouteImport.update({
  id: '/weakness',
  path: '/weakness',
  getParentRoute: () => PracticeRoute,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TestRoute,
} as any)
const TestDurationRoute = TestDurationRouteImport.update({
  id: '/$duration',
  path: '/$duration',
  getParentRoute: () => TestRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRoute
  '/placement': typeof PlacementRoute
  '/practice': typeof PracticeRouteWithChildren
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/statistics': typeof StatisticsRoute
  '/test': typeof TestRouteWithChildren
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/practice/accuracy': typeof PracticeAccuracyRoute
  '/practice/free': typeof PracticeFreeRoute
  '/practice/speed': typeof PracticeSpeedRoute
  '/practice/weakness': typeof PracticeWeaknessRoute
  '/test/$duration': typeof TestDurationRoute
  '/practice/': typeof PracticeIndexRoute
  '/test/': typeof TestIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRoute
  '/placement': typeof PlacementRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/statistics': typeof StatisticsRoute
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/practice/accuracy': typeof PracticeAccuracyRoute
  '/practice/free': typeof PracticeFreeRoute
  '/practice/speed': typeof PracticeSpeedRoute
  '/practice/weakness': typeof PracticeWeaknessRoute
  '/test/$duration': typeof TestDurationRoute
  '/practice': typeof PracticeIndexRoute
  '/test': typeof TestIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/achievements': typeof AchievementsRoute
  '/ai': typeof AiRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/learn': typeof LearnRoute
  '/placement': typeof PlacementRoute
  '/practice': typeof PracticeRouteWithChildren
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/shop': typeof ShopRoute
  '/statistics': typeof StatisticsRoute
  '/test': typeof TestRouteWithChildren
  '/lesson/$lessonId': typeof LessonLessonIdRoute
  '/practice/accuracy': typeof PracticeAccuracyRoute
  '/practice/free': typeof PracticeFreeRoute
  '/practice/speed': typeof PracticeSpeedRoute
  '/practice/weakness': typeof PracticeWeaknessRoute
  '/test/$duration': typeof TestDurationRoute
  '/practice/': typeof PracticeIndexRoute
  '/test/': typeof TestIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/achievements'
    | '/ai'
    | '/auth'
    | '/dashboard'
    | '/learn'
    | '/placement'
    | '/practice'
    | '/progress'
    | '/settings'
    | '/shop'
    | '/statistics'
    | '/test'
    | '/lesson/$lessonId'
    | '/practice/accuracy'
    | '/practice/free'
    | '/practice/speed'
    | '/practice/weakness'
    | '/test/$duration'
    | '/practice/'
    | '/test/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/achievements'
    | '/ai'
    | '/auth'
    | '/dashboard'
    | '/learn'
    | '/placement'
    | '/progress'
    | '/settings'
    | '/shop'
    | '/statistics'
    | '/lesson/$lessonId'
    | '/practice/accuracy'
    | '/practice/free'
    | '/practice/speed'
    | '/practice/weakness'
    | '/test/$duration'
    | '/practice'
    | '/test'
  id:
    | '__root__'
    | '/'
    | '/achievements'
    | '/ai'
    | '/auth'
    | '/dashboard'
    | '/learn'
    | '/placement'
    | '/practice'
    | '/progress'
    | '/settings'
    | '/shop'
    | '/statistics'
    | '/test'
    | '/lesson/$lessonId'
    | '/practice/accuracy'
    | '/practice/free'
    | '/practice/speed'
    | '/practice/weakness'
    | '/test/$duration'
    | '/practice/'
    | '/test/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AchievementsRoute: typeof AchievementsRoute
  AiRoute: typeof AiRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  LearnRoute: typeof LearnRoute
  PlacementRoute: typeof PlacementRoute
  PracticeRoute: typeof PracticeRouteWithChildren
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  ShopRoute: typeof ShopRoute
  StatisticsRoute: typeof StatisticsRoute
  TestRoute: typeof TestRouteWithChildren
  LessonLessonIdRoute: typeof LessonLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai': {
      id: '/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placement': {
      id: '/placement'
      path: '/placement'
      fullPath: '/placement'
      preLoaderRoute: typeof PlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice': {
      id: '/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof PracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof TestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lesson/$lessonId': {
      id: '/lesson/$lessonId'
      path: '/lesson/$lessonId'
      fullPath: '/lesson/$lessonId'
      preLoaderRoute: typeof LessonLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/practice/': {
      id: '/practice/'
      path: '/'
      fullPath: '/practice/'
      preLoaderRoute: typeof PracticeIndexRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/accuracy': {
      id: '/practice/accuracy'
      path: '/accuracy'
      fullPath: '/practice/accuracy'
      preLoaderRoute: typeof PracticeAccuracyRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/free': {
      id: '/practice/free'
      path: '/free'
      fullPath: '/practice/free'
      preLoaderRoute: typeof PracticeFreeRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/speed': {
      id: '/practice/speed'
      path: '/speed'
      fullPath: '/practice/speed'
      preLoaderRoute: typeof PracticeSpeedRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/practice/weakness': {
      id: '/practice/weakness'
      path: '/weakness'
      fullPath: '/practice/weakness'
      preLoaderRoute: typeof PracticeWeaknessRouteImport
      parentRoute: typeof PracticeRoute
    }
    '/test/': {
      id: '/test/'
      path: '/'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof TestRoute
    }
    '/test/$duration': {
      id: '/test/$duration'
      path: '/$duration'
      fullPath: '/test/$duration'
      preLoaderRoute: typeof TestDurationRouteImport
      parentRoute: typeof TestRoute
    }
  }
}

interface PracticeRouteChildren {
  PracticeAccuracyRoute: typeof PracticeAccuracyRoute
  PracticeFreeRoute: typeof PracticeFreeRoute
  PracticeSpeedRoute: typeof PracticeSpeedRoute
  PracticeWeaknessRoute: typeof PracticeWeaknessRoute
  PracticeIndexRoute: typeof PracticeIndexRoute
}

const PracticeRouteChildren: PracticeRouteChildren = {
  PracticeAccuracyRoute: PracticeAccuracyRoute,
  PracticeFreeRoute: PracticeFreeRoute,
  PracticeSpeedRoute: PracticeSpeedRoute,
  PracticeWeaknessRoute: PracticeWeaknessRoute,
  PracticeIndexRoute: PracticeIndexRoute,
}

const PracticeRouteWithChildren = PracticeRoute._addFileChildren(
  PracticeRouteChildren,
)

interface TestRouteChildren {
  TestDurationRoute: typeof TestDurationRoute
  TestIndexRoute: typeof TestIndexRoute
}

const TestRouteChildren: TestRouteChildren = {
  TestDurationRoute: TestDurationRoute,
  TestIndexRoute: TestIndexRoute,
}

const TestRouteWithChildren = TestRoute._addFileChildren(TestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AchievementsRoute: AchievementsRoute,
  AiRoute: AiRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  LearnRoute: LearnRoute,
  PlacementRoute: PlacementRoute,
  PracticeRoute: PracticeRouteWithChildren,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  ShopRoute: ShopRoute,
  StatisticsRoute: StatisticsRoute,
  TestRoute: TestRouteWithChildren,
  LessonLessonIdRoute: LessonLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
